CKAN_DB_SERVER: "adb-inventory-master-20180911221053071300000001.czspvxktlmh6.us-west-1.rds.amazonaws.com"
inventory_db_user: "ckan"
inventory_db_pass: "ckanpassword"
inventory_db_name: "ckan_inventory"
DATASTORE_DB_SERVER: "${db_inventory_datastore_master}"
inventory_datastore_db_name: "ckan_inventory"
inventory_datastore_user: "ckan"
inventory_datastore_pass: "ckanpassword"
inventory_datastore_ro_user: "ckan"
inventory_datastore_ro_pass: "ckanpassword"
