---
- name: get information on newest versions of packages and their dependencies
  apt: update_cache=yes

- name: make sure packages are installed
  action: apt pkg={{item}} state=installed
  with_items:
    - acl
    - atool
    - bison
    - git
    - htop
    - lib32z1-dev
    - libbz2-dev
    - libdb-dev
    - libffi-dev
    - libgdbm-dev
    - libgeos-c1
    - libpq-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - ntp
    - postgresql-client
    - python-dev
    - python-pip
    - python-setuptools
    - python-virtualenv
    - ruby
    - ruby-dev

# Build a more recent version of python than os provides
- include: python-upgrade.yml

# The Network Time Protocol is used to manage the system clock over a network
# If every system on a network reliably reports the same time, then it is much easier to correlate log messages in case of an attack

- name: be sure ntp is installed
  apt: name=ntp state=installed
  tags:
    - ntp

- name: be sure ntpd is running and enabled
  service: name=ntp state=started enabled=yes
  tags:
    - ntp
    - AU-8
