---
- name: Check if python dir exists
  stat: path=/{{ python_version_directory }}/bin/python
  register: python_dir

- name: Check if python was built with shared library
  stat: path=/{{ python_version_directory }}/lib/libpython{{ python_version_number[0:3] }}.so
  when: python_dir.stat.exists
  register: python_shared_lib

- name: Check if python was built with dbm
  command: /{{ python_version_directory }}/bin/python -c 'import dbm'
  when: python_dir.stat.exists
  register: python_dbm
  ignore_errors: true

- name: check to python version
  command: /{{ python_version_directory }}/bin/python --version
  register: python_version_check
  failed_when: ("Python " + python_version_number) not in python_version_check.stderr
  ignore_errors: True
  when: python_dir.stat.exists
  tags: skip_ansible_lint

- include: python-build.yml
  when: >-
    not python_dir.stat.exists or
    python_version_check is failed or
    python_dbm is failed or
    not python_shared_lib.stat.exists

  #TODO install python to a known prefix like /usr/local to avoid this
- name: add python lib to ld.so.conf
  template: src=etc/ld.so.conf.d/20python.conf dest=/etc/ld.so.conf.d/20python.conf
  register: ubuntu_python_ld_so

- name: update ld.so.cache
  command: ldconfig
  when: ubuntu_python_ld_so | changed
