---
# Global vars
# THESE ARE NOT DEFAULTS, THESE VARS OVERRIDE INVENTORY group_vars/*  !!!
# https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# Nginx
nginx_remove_default_vhost: true

# PHP-FPM
php_enable_php_fpm: true
php_webserver_daemon: nginx

# new python version
python_version_number: 2.7.10
python_version_name: Python-{{ python_version_number }}
python_version_url: https://www.python.org/ftp/python/{{ python_version_number}}/{{ python_version_name }}.tgz
python_version_directory: /usr/local/lib/python{{ python_version_number }}/
python_home: "{{ python_version_directory }}"

# Disabling MySQL server (we need only client on this machine)
mysql_enabled_on_startup: false

# PHP
php_memory_limit: 512M
php_expose_php: 0
php_fpm_pm_max_children: 200
php_fpm_pm_start_servers: 15
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 20
php_fpm_request_terminate_timeout: 30s
php_opcache_conf_filename: "10-opcache.ini"

# This should probably be environment specific
operators:
  - username: adborden
    email: aaron.borden@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFtWXnfXkTvUrcGxsColboVWfaRAB57vqA0zbsz3bHXh0XngTEaOrGiT3Eg9ep6a5YZJnsO83DIfdNllYWRE45PaJsAxcTKoBZ/KRJXCVODnj/H0CoccHFCUexOpIJWjCs4IjlGRgVnp9s7DMeh021XYVUE1CeXFFLZVLpbWpDC4PkmdolD3Lu/8LJ4YkXGSmEGvzf1eVneekW301g4fhIbI9k3zZSqknpIPjVh2ZNUNssJ0K8hRSuWbyE4neTXLUlJ9gdXLXIVbpPQW/ny56jz2h9G0ImLChHit80v19WEgCH3E84Bp7hiGz2q5tW5flTOcSluCd0n7xeD0zeh5wL datagov-adborden
  #- username: jjediny
  #  email: john.jediny@gsa.gov
  #  public_key: ''
