---
- name: install jumpbox packages
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    # These are mostly dependencies for datagov-deploy's requirements.txt
    - git
    - libffi-dev
    - libssl-dev
    - openssh-server
    - python-dev
    - python-pip
    - python-virtualenv

- name: Create/remove the user account
  user:
    name: "{{ item.username }}"
    comment: "{{ item.email }}"
    shell: /bin/bash
    state: "{{ item.removed is defined and 'absent' or 'present' }}"
    password_lock: yes
    expires: -1
  with_items: "{{ jumpbox_operators }}"

- name: Add SSH public key directory structure
  file: >-
    path=/home/{{ item.username }}/.ssh
    state=directory
    mode=0700
    owner={{ item.username }}
    group={{ item.username }}
  when: item.removed is undefined
  with_items: "{{ jumpbox_operators }}"

- name: Copy SSH public key
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_key }}"
    exclusive: True
    state: "present"
  when: item.removed is not defined
  with_items: "{{ jumpbox_operators }}"

- name: Update the system /etc/sudoers file
  template: >-
    src=sudoers.j2
    dest=/etc/sudoers.d/{{ item.username }}
    mode=0600
  when: item.removed is not defined
  with_items: "{{ jumpbox_operators }}"

- name: Remove sudoers for removed users
  file: >-
    dest=/etc/sudoers.d/{{ item.username }}
    state=absent
  when: item.removed is defined
  with_items: "{{ jumpbox_operators }}"

- name: Add SSH users to AllowUsers
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: '^AllowUsers'
    line: "AllowUsers {{ jumpbox_operators | selectattr('removed', 'undefined') | map(attribute='username') | join(' ') }}"
    state: present
  when: jumpbox_ssh_allow_users
  notify: restart sshd

- name: Add SSH users to AllowGroups
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: '^AllowGroups'
    line: "AllowGroups {{ jumpbox_operators | selectattr('removed', 'undefined') | map(attribute='username') | join(' ') }}"
    state: present
  when: jumpbox_ssh_allow_users
  notify: restart sshd
