---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  roles:
    - role: monitoring/newrelic/python-agent-ansible
      vars:
        nrinfragent_license_key: "{{ vault_nrinfragent_license_key }}"
