---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: jumpbox1
    image: ubuntu:trusty
    groups:
      - jumpbox
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ../../../..
  inventory:
    group_vars:
      jumpbox:
        operators:
          - username: testuser
            email: testuser@example.com
            public_key: ssh-rsa testuser-public-key-string comment
          - username: removeduser
            email: removeduser@example.com
            public_key: ssh-rsa removeduser-public-key-string comment
            removed: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
